server:
  port: 8989

#turbine:
#  aggregator:
#    clusterConfig: OMAR-WFS,OMAR-DOWNLOAD
#  appConfig: omar-wfs,omar-download

 turbine:
  appConfig: omar-wfs,omar-download
  clusterNameExpression: 'default'

logging:
  level: INFO
