apiVersion: v1
kind: DeploymentConfig
metadata:
  name: omar-turbine-server
  namespace: omar-dev
  selfLink: /oapi/v1/namespaces/omar-dev/deploymentconfigs/omar-turbine-server
  uid: 25ef05ad-a87d-11e7-ba3b-0e704fd9c8b2
  resourceVersion: '8818386'
  generation: 138
  creationTimestamp: '2017-10-03T20:55:11Z'
  labels:
    app: omar-turbine-server
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - omar-turbine-server
        from:
          kind: ImageStreamTag
          namespace: o2
          name: 'omar-turbine-server:latest'
        lastTriggeredImage: >-
          172.30.181.173:5000/o2/omar-turbine-server@sha256:36edd9a165b8b196693ca5fa2fee5658640784b33f63bda3fa587c1b14f29fb9
  replicas: 1
  test: false
  selector:
    app: omar-turbine-server
    deploymentconfig: omar-turbine-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omar-turbine-server
        deploymentconfig: omar-turbine-server
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: omar-turbine-server
          image: >-
            172.30.181.173:5000/o2/omar-turbine-server@sha256:36edd9a165b8b196693ca5fa2fee5658640784b33f63bda3fa587c1b14f29fb9
          ports:
            - containerPort: 8761
              protocol: TCP
            - containerPort: 8989
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'dev,production'
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: master
          resources: {}
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 121
  observedGeneration: 138
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: o2
            name: 'omar-turbine-server:latest'
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-10-31T19:42:24Z'
      lastTransitionTime: '2017-10-31T19:42:24Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2017-11-29T21:23:06Z'
      lastTransitionTime: '2017-11-29T21:23:01Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "omar-turbine-server-121" successfully rolled out
  readyReplicas: 1
